media:
  - name: files
    label: Files
    input: files/Documents
    output: files/documents
    categories: [ document ]
  - name: images # Note: 'name' key is required here
    label: files/Images
    input: files/images
    output: /images
    extensions: [ image ]
  - name: videos # Note: 'name' key is required here
    label: files/Videos
    input: files/videos
    output: /videos
    extensions: [ video ]
