media: media

content:
  - name: homepage
    label: Homepage
    path: src/homepage
    type: collection
    fields:
      - name: title
        label: Website title
        type: string
      - name: hero-text
        label: Hero Text
        type: string
      - name: hero-subtitle
        label: Hero subtitle
        type: string