media: media

content:
  - name: homepage
    label: Homepage
    type: collection
    path: '_home'
    view:
      fields: [ title, published, date ]
    fields:
      - name: title
        label: Title
        type: string
      - name: body
        label: Body
        type: rich-text