media:
  - name: files
    label: Files
    input: Documents
    output: documents
    categories: [ document ]
  - name: images # Note: 'name' key is required here
    label: Images
    input: images
    output: /images
    extensions: [ image ]
  - name: videos # Note: 'name' key is required here
    label: Videos
    input: videos
    output: /videos
    extensions: [ video ]
