media: media

content:

  - name: homepage
    label: Homepage
    path: content/homepage
    type: collection
    fields:
      - name: title
        label: Website Title
        type: string
      - name: hero-header
        label: Hero Header
        type: string
      - name: hero-subtitle
        label: Hero Subtitle
        type: string
      - name: mailchimp-embed-code
        label: Mailchimp Embed Code
        type: code
        options:
          language: html
      - name: live-shows-header
        label: Live Shows Header
        type: string
        
      - name: live-shows-block
        label: Live Shows Block
        type: block
        list: true
        blocks:
          - name: live-shows-block
            label: Live Shows Block
            component: live-shows-block
          
      - name: band-bio-header
        label: Band Bio Header
        type: string
      - name: band-bio-copy
        label: Band Bio Copy
        type: rich-text

  - name: live_shows
    label: Live Shows
    type: collection
    path: content/live-shows
    fields:
      - name: date
        label: Date
        type: date
      - name: location
        label: Location
        type: string
      - name: ticket_url
        label: Ticket Link
        type: string


components:
  live-shows-block:
      label: Live Shows Feed
      fields: []