media: media

content:
  - name: homepage
    label: Homepage
    path: src/homepage
    type: collection
    fields:
      - name: title
        label: Website Title
        type: string
      - name: hero-header
        label: Hero Header
        type: string
      - name: hero-subtitle
        label: Hero Subtitle
        type: string